2019-07-29T16:11:36.736-0400 I CONTROL  [initandlisten] MongoDB starting : pid=27080 port=27017 dbpath=/scratch/achattor/mongodb_storage/trial 64-bit host=bhg0040.bluehive.circ.private
2019-07-29T16:11:36.736-0400 I CONTROL  [initandlisten] db version v3.4.10
2019-07-29T16:11:36.736-0400 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2019-07-29T16:11:36.736-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten] modules: none
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten] build environment:
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten]     distmod: rhel70
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten]     distarch: x86_64
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2019-07-29T16:11:36.737-0400 I CONTROL  [initandlisten] options: { net: { port: 27017 }, storage: { dbPath: "/scratch/achattor/mongodb_storage/trial" } }
2019-07-29T16:11:36.804-0400 W -        [initandlisten] Detected unclean shutdown - /scratch/achattor/mongodb_storage/trial/mongod.lock is not empty.
2019-07-29T16:11:36.827-0400 I -        [initandlisten] Detected data files in /scratch/achattor/mongodb_storage/trial created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-07-29T16:11:36.827-0400 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2019-07-29T16:11:36.828-0400 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=63525M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2019-07-29T16:11:38.303-0400 I CONTROL  [initandlisten] 
2019-07-29T16:11:38.303-0400 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-07-29T16:11:38.303-0400 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-07-29T16:11:38.303-0400 I CONTROL  [initandlisten] 
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] 
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] 
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] 
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-07-29T16:11:38.304-0400 I CONTROL  [initandlisten] 
2019-07-29T16:11:38.526-0400 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/scratch/achattor/mongodb_storage/trial/diagnostic.data'
2019-07-29T16:11:38.527-0400 I NETWORK  [thread1] waiting for connections on port 27017
2019-07-29T16:11:39.028-0400 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2019-07-29T16:12:26.950-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:34850 #1 (1 connection now open)
2019-07-29T16:12:26.956-0400 I NETWORK  [conn1] received client metadata from 192.168.5.40:34850 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-07-29T16:12:27.031-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:34852 #2 (2 connections now open)
2019-07-29T16:12:27.034-0400 I NETWORK  [conn2] received client metadata from 192.168.5.40:34852 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-07-29T16:12:27.120-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:34854 #3 (3 connections now open)
2019-07-29T16:12:27.127-0400 I NETWORK  [conn3] received client metadata from 192.168.5.40:34854 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-07-29T16:12:27.187-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:34856 #4 (4 connections now open)
2019-07-29T16:12:27.194-0400 I NETWORK  [conn4] received client metadata from 192.168.5.40:34856 conn4: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-07-29T16:12:27.261-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:34858 #5 (5 connections now open)
2019-07-29T16:12:27.268-0400 I NETWORK  [conn5] received client metadata from 192.168.5.40:34858 conn5: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-07-29T16:12:38.546-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:34866 #6 (6 connections now open)
2019-07-29T16:12:38.546-0400 I NETWORK  [conn6] received client metadata from 192.168.5.40:34866 conn6: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-07-29T16:13:04.461-0400 I -        [conn4] end connection 192.168.5.40:34856 (6 connections now open)
2019-07-29T16:13:04.461-0400 I -        [conn6] end connection 192.168.5.40:34866 (6 connections now open)
2019-07-29T16:13:04.461-0400 I -        [conn5] end connection 192.168.5.40:34858 (6 connections now open)
2019-07-29T16:13:04.461-0400 I -        [conn2] end connection 192.168.5.40:34852 (6 connections now open)
2019-07-29T16:13:04.461-0400 I -        [conn1] end connection 192.168.5.40:34850 (6 connections now open)
2019-07-29T16:13:04.461-0400 I -        [conn3] end connection 192.168.5.40:34854 (6 connections now open)
